/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio_driver.h"
#include "keypad_driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx											= GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber					= GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode					= GPIO_MODE_OUTPUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed					= GPIO_SPEED_LOW;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType					= GPIO_OPTYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl			= GPIO_NO_PUPD;
	GpioLed.GPIO_PinConfig.GPIO_PinAltFunMode				= 0;
	GPIO_PeriClockControl(GPIOA, 1);
	GPIO_Init(&GpioLed);

	Keypad_Init();

	while(1)
	{
		char key = Keypad_Getkey();
		if(key != 0)
		{
			GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
		}
	}
}

